/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // misc: [{type: 'autogenerated', dirName: 'misc'}],
  suma: [{type: 'autogenerated', dirName: 'suma'}],
};

module.exports = sidebars;
