/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tec: [
    {type: 'autogenerated', dirName: 'tecnologia'},
    {
      type: 'link',
      label: 'GitHub Stars',
      href: 'https://github.com/smrsassa?tab=stars'
    }
  ],
  religiao: [{type: 'autogenerated', dirName: 'religiao'}],
  misc: [{type: 'autogenerated', dirName: 'misc'}],
};

module.exports = sidebars;
